# Generated by Django 3.2.3 on 2021-05-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210527_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='day_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='day_created',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
